### ISSUE TITLE
Steady versus Unsteady VLM

### ISSUE THREAD

**Issue by bharswami** [airinnova/pytornado#10]
Aaron
Won't there be a significant difference in force values between steady and the **settled** values of unsteady VLM?
Bharath

**Comment by aarondettmann** [comment]
Hello Bharath, I am not sure I understand your question correctly. Could you please try to rephrase your question. What do you mean with steady and settled values of the UVLM? And why would there be any difference in the force in your opinion?

Please note that PyTornado does not yet support UVLM analyses (though support for it would be desirable in the future).

**Comment by bharswami** [comment]
In steady VLM there is no time variation for the forces. There is just one
fixed value.
In unsteady VLM, the forces vary with time. It will asymptotically settle
to a value. My question is will this settled value be *exactly *same as the
steady VLM case.

**Comment by bharswami** [comment]
In comparing with my UVLM code and Matlab Tornado, I find that the forces
aren't *exact*.

**Comment by bharswami** [comment]
Could you please clarify this?

**Comment by aarondettmann** [comment]
Closed. Duplicate question, see issue #14
