### ISSUE TITLE
Using PyTornado

### ISSUE THREAD

**Issue by bharswami** [airinnova/pytornado#11]
Aren't results from PyTornado more accurate than Matlab Tornado?
I have the lattice structure from Matlab Tornado. I don't know how to use PyTornado. Can you help me out here?

**Comment by aarondettmann** [comment]
Please refer to the user guide which you can find here:

* https://pytornado.readthedocs.io/en/latest/user_guide/detailed_user_guide.html

Let me know if anything is unclear. Then I will try to help and update the documentation.

In general, PyTornado and Matlab Tornado are different implementations of the same mathematical model, so results should be the same. There are some minor differences in the discretization. Namely, Matlab Tornado uses so-called *horseshoe slings* whereas PyTornado uses standard *three-legged horseshoe vortices* (like in Drela or Katz and Plotkin). Minor, but practically negligible differences may be expected from these different discretizations.
