### ISSUE TITLE
Error while installing PyTornado

### ISSUE THREAD

**Issue by bharswami** [airinnova/pytornado#12]
```
 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Guset User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GUSETU~1\\AppData\\Local\\Temp\\pip-install-kscujy3m\\pytornado\\setup.py'"'"'; __file__='"'"'C:\\Users\\GUSETU~1\\AppData\\Local\\Temp\\pip-install-kscujy3m\\pytornado\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\GUSETU~1\AppData\Local\Temp\pip-install-kscujy3m\pytornado\pip-egg-info'
         cwd: C:\Users\GUSETU~1\AppData\Local\Temp\pip-install-kscujy3m\pytornado\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GUSETU~1\AppData\Local\Temp\pip-install-kscujy3m\pytornado\setup.py", line 90, in <module>
        packages=find_packages(where=PACKAGE_DIR),
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 71, in find
        convert_path(where),
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/lib/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by aarondettmann** [comment]
Thanks for reporting this. I don't have a Windows system available at the moment to test the installation myself. From your error log, I suspect that this error occurs because the file paths in ``setup.py`` are not of Windows style. I have added a fix for that.

Please try to install PyTornado with this latest fix (https://github.com/airinnova/pytornado/archive/master.zip) and let me know if the error still remains or if something else doesn't work.

**Comment by bharswami** [comment]
The command with the error pasted here:

**c:\Bharath\IIT PhD\Phase 3\Tornado\pytornado-master>pip install pytornado**
Collecting pytornado
  Using cached https://files.pythonhosted.org/packages/ee/39/8e2cc637772fc6e8fb4e518e3d926139aa3d32d62255981473a6fe93e270/pytornado-0.5.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\guset user\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Guset User\\AppData\\Local\\Temp\\pip-install-5p903tdx\\pytornado\\setup.py'"'"'; __file__='"'"'C:\\Users\\Guset User\\AppData\\Local\\Temp\\pip-install-5p903tdx\\pytornado\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Guset User\AppData\Local\Temp\pip-install-5p903tdx\pytornado\pip-egg-info'
         cwd: C:\Users\Guset User\AppData\Local\Temp\pip-install-5p903tdx\pytornado\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Guset User\AppData\Local\Temp\pip-install-5p903tdx\pytornado\setup.py", line 90, in <module>
        packages=find_packages(where=PACKAGE_DIR),
      File "c:\users\guset user\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 71, in find
        convert_path(where),
      File "c:\users\guset user\appdata\local\programs\python\python38\lib\distutils\util.py", line 124, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/lib/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by aarondettmann** [comment]
Could you please try again following these installation instructions:

* https://pytornado.readthedocs.io/en/latest/user_guide/installation.html

You will need to download the latest version here (https://github.com/airinnova/pytornado/archive/master.zip) and run ``pip install .`` in the PyTornado root directory. ``pip install pytornado`` does **not** work at the moment as pointed out here.

**Comment by bharswami** [comment]
I apparently need Visual C++ 14.0 which I am downloading now.
In the meantime, can you please get me the results for a simple aircraft geometry from PyTornado? I want to see if the results are different from Matlab Tornado. It will save me some time. I would really appreciate the help.

**Comment by bharswami** [comment]
Aaron
I was able to install PyTornado but I am getting the following error:
'pytornado' is not recognized as an internal or external command,
operable program or batch file.
Why is the command not being recognised?

**Comment by aarondettmann** [comment]
If you still get any error messages, it would help me if you can send them here, since I don't have a Windows machine to test the installation myself. Then I will be able to fix the installer and to update the documentation :)

How to generate a simple rectangular wing is described here: https://pytornado.readthedocs.io/en/latest/user_guide/getting_started.html The geometry and analysis can easily be set up in Matlab Tornado too. Numerical results can be found in the ``_results`` folder which will be generated when you run ``pytornado -v --run settings/template.json``.

**Comment by bharswami** [comment]
When I call pytornado, this is the error message:
'*pytornado' is not recognized as an internal or external command,*
*operable program or batch file.*

**Comment by aarondettmann** [comment]
This is a Windows issue. It has to do with where Windows looks for executable files. There is little I can do here I am afraid. Try to google the error, it seems to be a common with Python. It should also work to run ``python.exe C:\path\to\tornado`` (but I am not sure where *pip* installs its packages on Windows). See also:

* https://docs.python.org/3.7/using/windows.html

**Comment by bharswami** [comment]
Hi Aaron
Thanks. I am able to run pytornado by:
1. Changing the name of the file "pytornado" to something different -->
"pytornado_".
2. Calling the command "py pytornado_ --vr <path-to-settings-file>
Now I need another help. I have an aircraft configuration and I am having
trouble making the template file. Can you please make one for me so that I
can use it for other configurations in future?

**Comment by bharswami** [comment]
The reason I need your help is because I am getting wrong force values. I
think it's because of the setup file. Hope you can help me out.

**Comment by bharswami** [comment]
I was able to fix this.

**Comment by aarondettmann** [comment]
Glad to hear that the installation seemed to work now. Do you have any other issues with the installation procedure itself? Otherwise, I can try to help with your other questions in one of the other issues, and we close this one. We will try to address the issues with the installation on Windows that you reported here and update the installation scripts and documentation.

**Comment by bharswami** [comment]
Sounds good.

**Comment by bharswami** [comment]
Thanks for your help.
