### ISSUE TITLE
Lift Force

### ISSUE THREAD

**Issue by bharswami** [airinnova/pytornado#9]
In Matlab Tornado (or PyTornado) the total lift force is calculated across all surfaces or only the first wing? Is CL calculated using this lift force?

**Comment by aarondettmann** [comment]
Yes, the forces on _all_ surfaces (wings, horizontal/vertical tail etc.) are summed up into a _global_ force vector. This force vector is then transformed into the aerodynamic coordinate system to express lift, drag and the side force. A few more hints can be found here:

* https://pytornado.readthedocs.io/en/latest/theory/coordinate_systems.html
* https://pytornado.readthedocs.io/en/latest/theory/global_coeffs.html

In case you are interested in the code itself and potentially improving it, the summing of panel forces and transformation into the aerodynamic coordinate system is done here:

https://github.com/airinnova/pytornado/blob/0c88624e6a4f4629d136365c3aa8e31c2d538e73/src/lib/pytornado/aero/c_results.cpp#L38

**Comment by bharswami** [comment]
Thanks for your reply Aaron.
I have a code that computes Lift and Drag for each panel. The freestream is
in the negative x-direction. How to compute FX,FY,FZ,L,M,N.

**Comment by aarondettmann** [comment]
PyTornado computes both global forces in the _body-fixed coordinate system_ (Fx, Fy and Fz) as well as global forces in the _aerodynamic coordinate system_ (FL, FD, FC). These two systems differ if angle of attack and/or side slip angle are non-zero ([see](https://pytornado.readthedocs.io/en/latest/theory/coordinate_systems.html)). The transformation in PyTornado is implemented according to [1].

[1] _Drela, M.: Flight Vehicle Aerodynamics. Cambridge, Massachusetts: MIT Press, 2014. -- ISBN 978-0-262-52644-9_

**Comment by bharswami** [comment]
Thanks Aaron
